### ISSUE TITLE
RESET SAVE DATA not doing anything.

### ISSUE THREAD

**Issue by Jammington24** [lunarcleint/gorefield#4]
I was having issues figuring out my custom code, since I saw gameplays that got different hints than mines (example, someone got "the most repeated number of your highscore" as second hint, while I got "second digit of your accuracy in your highest score"). I thought "oh, maybe I read it wrong, but now I can't trigger the hint again to double check, so maybe I'll reset to get the screenshots of my hints".
The RESET SAVE DATA option does nothing; all my weeks and scores are intact.
This is after the March 16th patch.

Running on: Windows

**Comment by lunarcleint** [comment]
Yeah this is a issue with code name as a whole, we will look into it :D
